### ISSUE TITLE
Reduce the image size

### ISSUE THREAD

**Issue by roy2220** [reiz/nginx_proxy#10]
It would be great to shrink the image by [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds), smaller is better!

**Comment by reiz** [comment]
@roy2220 totally agree! Feel free to send a pull request ;-)

**Comment by pratikbalar** [comment]
@reiz I'm testing this with multistage, will do PR soon if time allows

cc: @roy2220

**Comment by pratikbalar** [comment]
https://github.com/reiz/nginx_proxy/pull/11

**Comment by roy2220** [comment]
@pratikbalar Thanks for your work.  I don't have much time to work on this
