### ISSUE TITLE
will it support nginx 1.17.*

### ISSUE THREAD

**Issue by ravikumarkgit** [reiz/nginx_proxy#2]
thanks for writing in about nginx forward proxy here.
i am using nginx 1.17., i have tried 1.16 connect patch but it's not working.
any thoughts on this?

**Comment by reiz** [comment]
@ravikumarkgit Pull this image: `docker pull reiz/nginx_proxy:0.0.3`. That contains Ubuntu 20.04 and Nginx 1.18.0.
