### ISSUE TITLE
manifest for reiz/nginx_proxy:0.0.1 not found

### ISSUE THREAD

**Issue by LinuxSuRen** [reiz/nginx_proxy#3]
I follow the document from readme file. But got the following errors
```
# docker run reiz/nginx_proxy:0.0.1
Unable to find image 'reiz/nginx_proxy:0.0.1' locally
docker: Error response from daemon: manifest for reiz/nginx_proxy:0.0.1 not found.
```

**Comment by reiz** [comment]
@LinuxSuRen Sorry for the confusion. The image is located here: https://hub.docker.com/r/reiz/nginx_proxy. But tagged as latest. Will fix it today!

**Comment by LinuxSuRen** [comment]
No worries.

**Comment by reiz** [comment]
@LinuxSuRen took a bit longer. But I just tagged and pushed version 0.0.1. See [here](https://hub.docker.com/layers/reiz/nginx_proxy/0.0.1/images/sha256-632bd2a91a7d196762735a39fe1a4fe2d38a040fea4842ae32dd24d7c30a4214?context=explore).
